version: '3.8'

services:
  backend:
    build: ./api
    container_name: pdf_qa_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  frontend:
    build: ./frontend
    container_name: pdf_qa_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env


